print("SET")
print("Duplicates are not allowed - duplicates will be removed")
print("Any datatype can be stored")
print("We can't modify set item but we can add or remove them")
print("Set is  unordered")
print("Set functions - add,remove,update,pop")
a={1,2,3,4,5,6,7,8,9,0}
print(type(a))
a.add(11)
print(a)
a.remove(11)
print(a)
a.pop()
print(a)
a.pop()
print(a)
a.pop()
print(a)